parameters:
- name: continueOnError
  type: boolean
  default: true
- name: trufflehogExclusionPathsFile
  type: string
  default: 'trufflehog.ignore'

stages:
- stage: secrets_scanning
  jobs:

  - job: gitsecrets
    continueOnError: ${{ parameters.continueOnError }}
    steps:
    - script: scan --from=azure-devops
      displayName: gitsecrets
    container: thefriendlypirate/git-secrets:azuredevops

  - job: trufflehog
    # to pass it as env var
    variables:
      trufflehog.Exclusion.Paths.File: ${{ parameters.trufflehogExclusionPathsFile }}
    continueOnError: ${{ parameters.continueOnError }}
    steps:
    - script: scan --from=azure-devops
      displayName: trufflehog
    container: thefriendlypirate/trufflehog:azuredevops