variables:
  SEC_GITSECRETS_IMAGE: thefriendlypirate/git-secrets:latest
  SEC_TRUFFLEHOG_IMAGE: thefriendlypirate/trufflehog:latest

.secrets-scanning:
  before_script: []

git-secrets:
  stage: secrets-scanning
  extends: .secrets-scanning
  image: ${SEC_GITSECRETS_IMAGE}
  script:
    - scan --from=gitlab-ci
  allow_failure: true

trufflehog:
  stage: secrets-scanning
  extends: .secrets-scanning
  image: ${SEC_TRUFFLEHOG_IMAGE}
  script:
    - scan --from=gitlab-ci
  allow_failure: true
